#!/usr/bin/env python3
"""
PyMOL ray-traced rendering scripts for GPCR–G protein interface figures.

Generates .pml scripts that can be run in PyMOL to produce publication-quality
ray-traced images of GPCR–G protein complex structures with BW-site highlighting.

Usage:
    python scripts/pymol_render.py              # generate .pml scripts
    pymol -cq figures/pymol/render_gq.pml       # run in PyMOL headless

Requires: PyMOL installed separately (not a Python dependency).
Recommended: PyMOL 2.5+ with ray tracing enabled.
"""
import os

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PYMOL_DIR = os.path.join(PROJECT_DIR, "figures", "pymol")
os.makedirs(PYMOL_DIR, exist_ok=True)

# BW positions that are FDR-significant
FDR_SITES_BW = ["34.50", "34.53", "3.53", "5.65", "5.71"]

# Representative structures for each coupling type
STRUCTURES = {
    "Gq": [
        {"pdb": "7DFL", "receptor": "5-HT2A", "galpha": "Gq",
         "receptor_chain": "A", "galpha_chain": "B"},
    ],
    "Gi": [
        {"pdb": "6CMO", "receptor": "mu-opioid", "galpha": "Gi",
         "receptor_chain": "R", "galpha_chain": "G"},
    ],
    "Gs": [
        {"pdb": "3SN6", "receptor": "beta2AR", "galpha": "Gs",
         "receptor_chain": "R", "galpha_chain": "A"},
    ],
}

# Approximate residue numbers for FDR-significant BW sites in 5-HT2A (7DFL)
# These should be verified against GPCRdb for each structure
BW_RESIDUE_MAP_7DFL = {
    "34.50": 161,  # ICL2
    "34.53": 164,
    "3.53":  172,  # TM3
    "5.65":  288,  # TM5
    "5.71":  294,
}

NATURE_BLUE = "0x0072B2"
NATURE_RED = "0xD55E00"
NATURE_GREEN = "0x009E73"
NATURE_ORANGE = "0xE69F00"


def generate_interface_pml(pdb_id, receptor_chain, galpha_chain,
                            bw_residues, output_name, coupling_type):
    """Generate a PyMOL .pml script for interface visualization."""

    residue_sel = "+".join(str(r) for r in bw_residues.values())

    script = f"""# PyMOL rendering script for {pdb_id} ({coupling_type} coupling)
# Generated by LeakageGuard render_figures.py
# Run: pymol -cq {output_name}.pml

# ── Setup ────────────────────────────────────────────────────────────────
reinitialize
set ray_shadow, 0
set ray_trace_mode, 1
set ray_trace_gain, 0.1
set ray_opaque_background, 1
set antialias, 2
set hash_max, 300
bg_color white

# ── Load structure ───────────────────────────────────────────────────────
fetch {pdb_id}, async=0
remove solvent
remove organic

# ── Colour by chain ──────────────────────────────────────────────────────
color grey80, chain {receptor_chain}
color {NATURE_GREEN}, chain {galpha_chain}

# ── Show receptor as cartoon ─────────────────────────────────────────────
hide everything
show cartoon, chain {receptor_chain}
show cartoon, chain {galpha_chain}
set cartoon_transparency, 0.3, chain {galpha_chain}

# ── Highlight FDR-significant BW sites ───────────────────────────────────
select bw_sites, chain {receptor_chain} and resi {residue_sel}
show sticks, bw_sites
color {NATURE_RED}, bw_sites
set stick_radius, 0.15, bw_sites
label bw_sites and name CA, "%s%s" % (resn, resi)
set label_size, 12
set label_color, black

# ── Interface contact residues (4Å) ─────────────────────────────────────
select interface, (chain {receptor_chain} within 4.0 of chain {galpha_chain}) \\
    and not bw_sites
show sticks, interface
color {NATURE_BLUE}, interface
set stick_radius, 0.10, interface

# ── Camera ───────────────────────────────────────────────────────────────
orient chain {receptor_chain}
zoom chain {receptor_chain}, 5
turn y, 30
turn x, -10

# ── Ray trace and save ──────────────────────────────────────────────────
set ray_trace_frames, 1
ray 2400, 1800
png {output_name}.png, dpi=600
save {output_name}.pse

print "Rendered: {output_name}.png"
quit
"""
    return script


def main():
    print("=" * 64)
    print("  Generating PyMOL Rendering Scripts")
    print("=" * 64)

    for coupling_type, structures in STRUCTURES.items():
        for s in structures:
            pdb = s["pdb"]
            name = f"render_{coupling_type.lower()}_{pdb}"
            out_path = os.path.join(PYMOL_DIR, name)

            # Use 7DFL residue map for Gq, placeholder for others
            if pdb == "7DFL":
                bw_res = BW_RESIDUE_MAP_7DFL
            else:
                bw_res = {k: 999 for k in FDR_SITES_BW}
                print(f"  WARNING: {pdb} BW residue numbers are placeholders. "
                      f"Verify from GPCRdb before rendering.")

            script = generate_interface_pml(
                pdb, s["receptor_chain"], s["galpha_chain"],
                bw_res, out_path, coupling_type,
            )

            pml_path = f"{out_path}.pml"
            with open(pml_path, "w") as f:
                f.write(script)
            print(f"  Written: {pml_path}")

    print(f"\n  To render, run each .pml in PyMOL:")
    print(f"    pymol -cq figures/pymol/render_gq_7DFL.pml")
    print(f"\n  For publication quality, use PyMOL > ray 3600, 2700")
    print(f"  Then refine labels/annotations in Adobe Illustrator.")
    print("=" * 64)


if __name__ == "__main__":
    main()
